TOPDIR=../..

SUBDIRS=.

TARGET_LIB:=libvscript_rtl.a

# name of additional libries
ADD_LIBRARIES:=

ADD_INCLUDES:=-I. -I$(TOPDIR)/vlib/inc -I$(TOPDIR)/vscript/inc -I$(TOPDIR)/vscript/rtl/inc -I$(TOPDIR)/vscript/src

include $(TOPDIR)/rules.make
