TOPDIR=../..

SUBDIRS=.

TARGET_LIB:=libvscript.a

# name of additional libries
ADD_LIBRARIES:=

ADD_INCLUDES:=-I.  -I$(TOPDIR)/vscript/inc -I$(TOPDIR)/vlib/inc

include $(TOPDIR)/rules.make
