TOPDIR=../..

SUBDIRS=.

TARGET_EXE:=vscripttest

# name of additional libries
ADD_LIBRARIES:=-lvscript -lvscript_rtl -lvutil -lvmemalloc -lvwrapper -lm

ADD_INCLUDES:=-I. -I$(TOPDIR)/vlib/inc -I$(TOPDIR)/vscript/inc -I$(TOPDIR)/vscript/rtl/inc -lm

include $(TOPDIR)/rules.make
