del /s /q *.zip
del /s /q *.obj
del /s /q *.dll
del /s /q *.exe
del /s /q *.lib
del /s /q *.bak
del /s /q *.pch
del /s /q *.pdb
del /s /q *.idb
del /s /q *.res
del /s /q *.sbr
del /s /q *.bsc
del /s /q *.tlb
del /s /q *.tli
del /s /q *.tlh
del /s /q *.ncb
del /s /q *.opt
del /s /q *.ilk
del /s /q *.plg
del /s /q *.exp
del /s /q vlib\doc\*