TOPDIR:=.

# subdirectories that contain our %.o files
SUBDIRS:=vlib/util\
	 vlib/memalloc\
	 vlib/wrapper/linux\
	 vtest/src\
	 vlib/test\
	 vscript/src\
	 vscript/rtl\
	 vscript/test
 
# subdirectories that contain unit tests
#TESTDIRS:=tests

# include top make
include $(TOPDIR)/rules.make


