TOPDIR=../..

SUBDIRS=.

TARGET_EXE:=test

# name of additional libries
ADD_LIBRARIES:=-lvutil -lvwrapper -lvtest -lvmemalloc -lvwrapper

ADD_INCLUDES:=-I. -I$(TOPDIR)/vlib/inc -I$(TOPDIR)/vtest/inc

include $(TOPDIR)/rules.make
